### ISSUE TITLE
DI/IoC comparisons

### ISSUE THREAD

**Issue by mwpowellhtx** [ZolutionSoftware/Rezolver#18]
Hello,

I am always interested to discover new, potentially better performing, containers for my DI needs. So, curious, how does Rezolver stack up in benchmarks? i.e. don't just claim high performance; show some benchmarks how it stacks up.

Of course, it is also interesting how this supports the Core / Standard migration path. And it still supports the sort of "conventional" / "classical" .NET Framework distributions?

That is until Core / Standard "way" catches on.

Thank you!

**Comment by LordZoltan** [comment]
Hi there!  Thanks for taking the time to stop by :)

So, yes - this supports the full .Net desktop profile as well as .Net Core profile.  I need to fire up a Xamarin project and check that it definitely does work on Android/iOS too - but since it only requires .NetStandard 1.1, then it *should* do.

*I intend to add many more examples after I've straightened out the smelly bits of the API and finished the core docs :)*

On to performance - you're absolutely right: saying, in the most recent release '25% faster' doesn't mean anything if I don't publish *actual* numbers!

So I'm currently running the [IOCPerformance](https://github.com/ZolutionSoftware/IocPerformance/tree/rezolver) benchmark I've forked from @DanielPalme with the necessary adapter added for Rezolver and will publish the results - including some analysis of the places where it's slow (and what I intend to do about it) - over on [the website](http://rezolver.co.uk) as soon as I can.

* * *
One of the features of Rezolver is that the process of turning a registration into executable code is handled by *injecting* a compiler ([the ITargetCompiler interface](http://rezolver.co.uk/developers/api/Rezolver.Compilation.ITargetCompiler.html)) into the container itself.  Thus, different ways of compiling can be tested, compared and even combined.  Indeed, that is key to how I intend to improve the performance of the parts which are currently slow.
* * *
I will update here once I've uploaded the benchmark results so you can see for yourself - and please don't hesitate to fire back any other questions you have!

Cheers,

Andras

**Comment by mwpowellhtx** [comment]
@LordZoltan Thanks for the prompt reply! Good to know, great to hear. I am currently a subscriber for Autofac as a reasonably well established, mature, and ubiquitous container. But if there's a better one here or on the horizon, who knows, container tech being what it is. I'll be interested to pop in from time to time and see what progress there is. Thanks again!

**Comment by mwpowellhtx** [comment]
[Pretty decent performance numbers](http://github.com/danielpalme/IocPerformance) stacking up against some popular ones, and especially the sort of "boilerplate" Microsoft ones, MEF, Unity, Ninject, even Autofac isn't quite as good. I haven't demo'd yours yet, per se, so I can't speak to features parity, on the other hand.

**Comment by LordZoltan** [comment]
Indeed!  The 'established' containers don't exactly shower themselves in glory!

The benchmark run has just finished and I have the results.

I can't release rezolver.co.uk at the moment as it would mean publishing a copy of the site for a version of the API which hasn't actually been released, so I will add an .md file here with each individual test result and the overviews, with some notes, in the next hour or so :)

**Comment by LordZoltan** [comment]
Hi there!

As promised, here are [the results of today's benches](https://github.com/ZolutionSoftware/Rezolver/blob/1.1.71702.100/doc/Rezolver.Documentation/_docfx_proj/docs/benchmarks.md)

Rezolver holds its own at around position 10-ish for the stuff that it supports!  

All the best,

Andras
